/**
 * Philippine provinces → cities/municipalities reference data for the report
 * wizard's City & Province dropdowns.
 *
 * `PH_PROVINCES` lists every province (plus "Metro Manila (NCR)"), and
 * `PH_CITIES_BY_PROVINCE` maps each province to its cities and capital/major
 * municipalities. Highly-urbanized cities geographically inside a province
 * (e.g. Davao City, Baguio City) are listed under that province so the
 * dropdowns always have a home for them.
 *
 * The lists intentionally tolerate unknown values at the UI layer: a value
 * that doesn't match (e.g. from draft restore or map reverse-geocoding) is
 * appended as an extra option instead of being dropped.
 */

export const PH_PROVINCES: string[] = [
  "Abra", "Agusan del Norte", "Agusan del Sur", "Aklan", "Albay", "Antique",
  "Apayao", "Aurora", "Basilan", "Bataan", "Batanes", "Batangas", "Benguet",
  "Biliran", "Bohol", "Bukidnon", "Bulacan", "Cagayan", "Camarines Norte",
  "Camarines Sur", "Camiguin", "Capiz", "Catanduanes", "Cavite", "Cebu",
  "Cotabato", "Davao de Oro", "Davao del Norte", "Davao del Sur",
  "Davao Occidental", "Davao Oriental", "Dinagat Islands", "Eastern Samar",
  "Guimaras", "Ifugao", "Ilocos Norte", "Ilocos Sur", "Iloilo", "Isabela",
  "Kalinga", "La Union", "Laguna", "Lanao del Norte", "Lanao del Sur",
  "Leyte", "Maguindanao del Norte", "Maguindanao del Sur", "Marinduque",
  "Masbate", "Metro Manila (NCR)", "Misamis Occidental", "Misamis Oriental",
  "Mountain Province", "Negros Occidental", "Negros Oriental",
  "Northern Samar", "Nueva Ecija", "Nueva Vizcaya", "Occidental Mindoro",
  "Oriental Mindoro", "Palawan", "Pampanga", "Pangasinan", "Quezon",
  "Quirino", "Rizal", "Romblon", "Samar", "Sarangani", "Siquijor",
  "Sorsogon", "South Cotabato", "Southern Leyte", "Sultan Kudarat", "Sulu",
  "Surigao del Norte", "Surigao del Sur", "Tarlac", "Tawi-Tawi", "Zambales",
  "Zamboanga del Norte", "Zamboanga del Sibugay", "Zamboanga del Sur",
];

export const PH_CITIES_BY_PROVINCE: Record<string, string[]> = {

  "Abra": ["Bangued", "Bucay", "Dolores", "La Paz", "Lagangilang", "Lagayan", "Luba", "Malibcong", "Manabo", "Peñarrubia", "Pidigan", "Pilar", "Sallapadan", "San Isidro", "San Juan", "San Quintin", "Tayum", "Tineg", "Tubo", "Villaviciosa", "Boliney", "Bucloc", "Daguioman", "Langiden", "Licuan-Baay"],
  "Agusan del Norte": ["Butuan City", "Cabadbaran City", "Buenavista", "Carmen", "Jabonga", "Kitcharao", "Las Nieves", "Magallanes", "Nasipit", "Santiago", "Tubay", "Remedios T. Romualdez"],
  "Agusan del Sur": ["Bayugan City", "Prosperidad", "San Francisco", "Talacogon", "Bunawan", "Esperanza", "Rosario", "Trento", "Veruela", "Sibagat", "Santa Josefa", "Loreto", "La Paz"],
  "Aklan": ["Kalibo", "Malay", "Nabas", "New Washington", "Banga", "Batan", "Libacao", "Madalag", "Makato", "Malinao", "Numancia", "Lezo", "Tangalan", "Ibajay", "Buruanga", "Altavas"],
  "Albay": ["Legazpi City", "Ligao City", "Tabaco City", "Daraga", "Camalig", "Guinobatan", "Jovellar", "Libon", "Malinao", "Malilipot", "Manito", "Oas", "Pio Duran", "Polangui", "Rapu-Rapu", "Santo Domingo", "Bacacay", "Tiwi"],
  "Antique": ["San Jose de Buenavista", "Sibalom", "Hamtic", "Patnongon", "Belison", "Bugasong", "Barbaza", "Laua-an", "Tibiao", "Culasi", "Sebaste", "Pandan", "Libertad", "Caluya", "Anini-y", "Tobias Fornier", "Valderrama"],
  "Apayao": ["Kabugao", "Luna", "Pudtol", "Flora", "Santa Marcela", "Conner", "Calanasan"],
  "Aurora": ["Baler", "Maria Aurora", "Dipaculao", "Casiguran", "Dingalan", "San Luis", "Dinalungan", "Dolores"],
  "Basilan": ["Isabela City", "Lamitan City", "Lantawan", "Maluso", "Sumisip", "Tipo-Tipo", "Tuburan", "Ungkaya Pukan", "Akbar", "Al-Barka", "Hadji Mohammad Ajul", "Tabuan-Lasa"],
  "Bataan": ["Balanga City", "Dinalupihan", "Hermosa", "Orani", "Samal", "Abucay", "Pilar", "Orion", "Limay", "Mariveles", "Morong", "Bagac"],
  "Batanes": ["Basco", "Itbayat", "Ivana", "Mahatao", "Sabtang", "Uyugan"],
  "Batangas": ["Batangas City", "Lipa City", "Tanauan City", "Santo Tomas City", "Calaca City", "Bauan", "San Pascual", "Mabini", "Tingloy", "Lemery", "Taal", "San Luis", "Alitagtag", "Cuenca", "Mataasnakahoy", "Balete", "Malvar", "Rosario", "Taysan", "Padre Garcia", "San Juan", "Lobo", "Tuy", "Balayan", "Calatagan", "Lian", "Nasugbu", "Laurel", "Agoncillo", "San Nicolas", "Santa Teresita"],
  "Benguet": ["La Trinidad", "Baguio City", "Itogon", "Tuba", "Tublay", "Atok", "Kibungan", "Kapangan", "Mankayan", "Buguias", "Bakun", "Sablan"],
  "Biliran": ["Naval", "Caibiran", "Culaba", "Almeria", "Kawayan", "Maripipi", "Cabucgayan", "Biliran"],
  "Bohol": ["Tagbilaran City", "Tubigon", "Jagna", "Ubay", "Talibon", "Carmen", "Loon", "Panglao", "Dauis", "Baclayon", "Inabanga", "Getafe", "Clarin", "Loay", "Dimiao", "Valencia", "Garcia Hernandez", "Guindulman", "Anda", "Candijay", "Mabini", "San Miguel", "Trinidad", "Bien Unido", "Buenavista", "Calape", "Catigbian", "Antequera", "Balilihan", "Batuan", "Bilar", "Corella", "Cortes", "Danao", "Duero", "Loboc", "Sevilla", "Sagbayan", "Alicia"],
  "Bukidnon": ["Malaybalay City", "Valencia City", "Maramag", "Quezon", "Manolo Fortich", "Impasugong", "Cabanglasan", "San Fernando", "Kibawe", "Dangcagan", "Damulog", "Kadingilan", "Pangantucan", "Kalilangan", "Baungon", "Libona", "Talakag", "Sumilao", "Don Carlos", "Kitaotao", "Lantapan"],
  "Bulacan": ["Malolos City", "San Jose del Monte City", "Meycauayan City", "Baliwag", "Plaridel", "Hagonoy", "Calumpit", "Pulilan", "Santa Maria", "Marilao", "Bocaue", "Angat", "San Rafael", "San Ildefonso", "Doña Remedios Trinidad", "Norzagaray", "Pandi", "Guiguinto", "Balagtas", "Bustos", "Paombong", "Obando", "San Miguel"],
  "Cagayan": ["Tuguegarao City", "Aparri", "Gonzaga", "Lal-lo", "Camalaniugan", "Buguey", "Santa Ana", "Sanchez-Mira", "Pamplona", "Abulug", "Ballesteros", "Amulung", "Iguig", "Peñablanca", "Enrile", "Solana", "Piat", "Tuao", "Rizal", "Lasam", "Gattaran", "Alcala", "Santo Niño", "Allacapan", "Claveria"],
  "Camarines Norte": ["Daet", "Labo", "Jose Panganiban", "Paracale", "Vinzons", "Mercedes", "Basud", "Capalonga", "Santa Elena", "San Vicente", "Talisay", "San Lorenzo Ruiz"],
  "Camarines Sur": ["Naga City", "Iriga City", "Pili", "Nabua", "Bato", "Buhi", "Tigaon", "Ocampo", "Calabanga", "Canaman", "Magarao", "Milaor", "Minalabac", "Pamplona", "Pasacao", "San Fernando", "Sipocot", "Lupi", "Ragay", "Del Gallego", "Libmanan", "Cabusao", "Caramoan", "Goa", "Lagonoy", "Presentacion", "San Jose", "Sagñay", "Siruma", "Baao", "Balatan", "Bula"],
  "Camiguin": ["Mambajao", "Mahinog", "Guinsiliban", "Sagay", "Catarman"],
  "Capiz": ["Roxas City", "Pontevedra", "Panay", "Panitan", "Maayon", "Cuartero", "Dao", "Dumalag", "Dumarao", "Ivisan", "Jamindan", "Mambusao", "Pilar", "President Roxas", "Sigma", "Tapaz", "Sapi-an"],
  "Catanduanes": ["Virac", "San Andres", "Bato", "Baras", "Gigmoto", "Pandan", "Panganiban", "Bagamanoc", "Caramoran", "Viga"],
  "Cavite": ["Cavite City", "Tagaytay City", "Bacoor City", "Dasmariñas City", "Imus City", "General Trias City", "Trece Martires City", "Tanza", "Rosario", "Noveleta", "Kawit", "Silang", "Amadeo", "Mendez", "Alfonso", "General Emilio Aguinaldo", "Magallanes", "Maragondon", "Ternate", "Naic", "Indang", "Carmona", "General Mariano Alvarez"],
  "Cebu": ["Cebu City", "Mandaue City", "Lapu-Lapu City", "Talisay City", "Toledo City", "Danao City", "Naga City", "Carcar City", "Bogo City", "Minglanilla", "Consolacion", "Liloan", "Compostela", "Cordova", "San Fernando", "Pinamungajan", "Barili", "Dumanjug", "Ronda", "Alcantara", "Moalboal", "Badian", "Alegria", "Malabuyoc", "Ginatilan", "Santander", "Samboan", "Oslob", "Boljoon", "Dalaguete", "Alcoy", "Argao", "Sibonga", "Bantayan", "Madridejos", "Santa Fe", "Daanbantayan", "San Remigio", "Tabogon", "Borbon", "Sogod", "Catmon", "Carmen", "Asturias", "Balamban", "Aloguinsan"],
  "Cotabato": ["Kidapawan City", "Midsayap", "Kabacan", "Pigcawayan", "Pikit", "Aleosan", "Banisilan", "Carmen", "Libungan", "M'lang", "Magpet", "Arakan", "Antipas", "President Roxas", "Alamada", "Tulunan", "Matalam"],
  "Davao de Oro": ["Nabunturan", "Compostela", "Monkayo", "Montevista", "New Bataan", "Mawab", "Maco", "Maragusan", "Mabini", "Pantukan", "Laak"],
  "Davao del Norte": ["Tagum City", "Panabo City", "Island Garden City of Samal", "Santo Tomas", "Kapalong", "Asuncion", "San Isidro", "Carmen", "Braulio E. Dujali", "New Corella", "Talaingod"],
  "Davao del Sur": ["Digos City", "Davao City", "Santa Cruz", "Bansalan", "Hagonoy", "Padada", "Malalag", "Sulop", "Kiblawan", "Magsaysay", "Matanao"],
  "Davao Occidental": ["Malita", "Don Marcelino", "Jose Abad Santos", "Sarangani", "Santa Maria"],
  "Davao Oriental": ["Mati City", "Lupon", "Banaybanay", "Governor Generoso", "San Isidro", "Cateel", "Baganga", "Caraga", "Manay", "Tarragona", "Boston"],
  "Dinagat Islands": ["San Jose", "Basilisa", "Cagdianao", "Dinagat", "Libjo", "Loreto", "Tubajon"],
  "Eastern Samar": ["Borongan City", "Guiuan", "Dolores", "Oras", "Can-avid", "Sulat", "Taft", "San Julian", "Hernani", "General MacArthur", "Llorente", "Balangiga", "Giporlos", "Quinapondan", "Salcedo", "Mercedes", "Maslog", "Arteche", "Jipapad", "Lawaan"],
  "Guimaras": ["Jordan", "Buenavista", "Nueva Valencia", "San Lorenzo", "Sibunag"],
  "Ifugao": ["Lagawe", "Banaue", "Kiangan", "Hungduan", "Mayoyao", "Aguinaldo", "Hingyon", "Lamut", "Asipulo", "Alfonso Lista", "Tinoc"],
  "Ilocos Norte": ["Laoag City", "Batac City", "Vintar", "Bacarra", "Paoay", "San Nicolas", "Sarrat", "Dingras", "Bangui", "Burgos", "Pagudpud", "Adams", "Dumalneg", "Carasi", "Marcos", "Nueva Era", "Pinili", "Badoc", "Currimao", "Piddig", "Solsona"],
  "Ilocos Sur": ["Vigan City", "Candon City", "Bantay", "Santa", "Caoayan", "Magsingal", "Santo Domingo", "San Ildefonso", "San Vicente", "Sinait", "Cabugao", "San Juan", "Santiago", "Narvacan", "Santa Maria", "Burgos", "Santa Lucia", "Salcedo", "Sigay", "Gregorio Del Pilar", "Quirino", "Cervantes", "Suyo", "Tagudin", "Alilem", "Banayoyo", "Lidlidda", "Sugpon", "San Emilio", "Galimuyod", "Santa Cruz"],
  "Iloilo": ["Iloilo City", "Passi City", "Oton", "Pavia", "Leganes", "Santa Barbara", "Cabatuan", "Janiuay", "Pototan", "Dingle", "Duenas", "San Enrique", "Lambunao", "Calinog", "Bingawan", "Badiangan", "Miagao", "Guimbal", "Tigbauan", "San Miguel", "Leon", "Alimodian", "Zarraga", "Barotac Nuevo", "Dumangas", "Anilao", "Banate", "Barotac Viejo", "Ajuy", "Sara", "San Dionisio", "Concepcion", "Batad", "Lemery", "Balasan", "Estancia", "Carles", "San Rafael", "Maasin", "New Lucena", "Mina"],
  "Isabela": ["Ilagan City", "Cauayan City", "Santiago City", "Echague", "Roxas", "Cordon", "Ramon", "San Mateo", "Aurora", "Cabagan", "San Pablo", "Tumauini", "Delfin Albano", "Santo Tomas", "Quezon", "Mallig", "Quirino", "Burgos", "Gamu", "Naguilian", "Benito Soliven", "San Mariano", "Palanan", "Dinapigue", "Maconacon", "Divilacan", "Santa Maria", "Jones", "San Agustin", "San Guillermo", "Angadanan", "Alicia", "Luna", "Reina Mercedes", "Cabatuan", "San Manuel"],
  "Kalinga": ["Tabuk City", "Balbalan", "Lubuagan", "Pasil", "Pinukpuk", "Rizal", "Tanudan", "Tinglayan"],
  "La Union": ["San Fernando City", "Bauang", "Caba", "Aringay", "Agoo", "Tubao", "Santo Tomas", "Rosario", "Pugo", "Burgos", "Naguilian", "Bagulin", "San Gabriel", "San Juan", "Bacnotan", "Balaoan", "Luna", "Santol", "Sudipen", "Bangar"],
  "Laguna": ["Santa Rosa City", "Calamba City", "Cabuyao City", "San Pablo City", "Biñan City", "San Pedro City", "Santa Cruz", "Los Baños", "Bay", "Calauan", "Victoria", "Pila", "Magdalena", "Majayjay", "Luisiana", "Cavinti", "Lumban", "Kalayaan", "Paete", "Pakil", "Pangil", "Siniloan", "Famy", "Mabitac", "Santa Maria", "Pagsanjan", "Nagcarlan", "Liliw", "Rizal", "Alaminos"],
  "Lanao del Norte": ["Iligan City", "Tubod", "Kapatagan", "Baroy", "Lala", "Salvador", "Bacolod", "Maigo", "Kolambugan", "Linamon", "Munai", "Nunungan", "Pantao Ragat", "Poona Piagapo", "Tagoloan", "Tangcal", "Matungao", "Pantar", "Balo-i"],
  "Lanao del Sur": ["Marawi City", "Wao", "Bubong", "Ditsaan-Ramain", "Marantao", "Saguiaran", "Tugaya", "Bacolod-Kalawi", "Balabagan", "Binidayan", "Butig", "Ganassi", "Kapai", "Lumbatan", "Madalum", "Madamba", "Maguing", "Malabang", "Masiu", "Pagayawan", "Piagapo", "Taraka", "Tamparan", "Tubaran"],
  "Leyte": ["Tacloban City", "Ormoc City", "Baybay City", "Palo", "Tanauan", "Tolosa", "Dulag", "Julita", "Tabontabon", "Burauen", "Alangalang", "Jaro", "Tunga", "San Miguel", "Santa Fe", "Albuera", "Merida", "Isabel", "Matag-ob", "Palompon", "Villaba", "Kananga", "Calubian", "San Isidro", "Capoocan", "Carigara", "Barugo", "Babatngon", "Dagami", "Pastrana", "Mayorga", "MacArthur", "Abuyog", "Javier", "Mahaplag", "Hilongos", "Bato", "Matalom", "Hindang", "Inopacan", "La Paz", "Leyte"],
  "Maguindanao del Norte": ["Datu Odin Sinsuat", "Parang", "Barira", "Buldon", "Matanog", "Sultan Kudarat", "Kabuntalan", "Northern Kabuntalan", "Datu Blah T. Sinsuat", "Upi", "South Upi", "Sultan Mastura"],
  "Maguindanao del Sur": ["Buluan", "Datu Paglas", "Datu Piang", "Datu Saudi-Ampatuan", "Datu Unsay", "General Salipada K. Pendatun", "Guindulungan", "Mamasapano", "Mangudadatu", "Pagalungan", "Paglat", "Rajah Buayan", "Shariff Aguak", "Shariff Saydona Mustapha", "Talayan", "Ampatuan", "Pandag", "Datu Abdullah Sangki", "Sultan sa Barongis"],
  "Marinduque": ["Boac", "Mogpog", "Gasan", "Buenavista", "Torrijos", "Santa Cruz"],
  "Masbate": ["Masbate City", "Aroroy", "Baleno", "Milagros", "Mandaon", "Mobo", "Balud", "Uson", "Cawayan", "Placer", "Esperanza", "Pio V. Corpuz", "Cataingan", "Palanas", "Dimasalang", "Monreal", "Batuan", "San Jacinto", "San Pascual", "Claveria"],
  "Metro Manila (NCR)": ["Caloocan City", "Las Piñas City", "Makati City", "Malabon City", "Mandaluyong City", "Manila City", "Marikina City", "Muntinlupa City", "Navotas City", "Parañaque City", "Pasay City", "Pasig City", "Pateros", "Quezon City", "San Juan City", "Taguig City", "Valenzuela City"],
  "Misamis Occidental": ["Ozamiz City", "Oroquieta City", "Tangub City", "Tudela", "Sinacaban", "Jimenez", "Clarin", "Aloran", "Panaon", "Lopez Jaena", "Plaridel", "Baliangao", "Calamba", "Don Victoriano", "Concepcion", "Bonifacio", "Sapang Dalaga"],
  "Misamis Oriental": ["Cagayan de Oro City", "Gingoog City", "El Salvador City", "Tagoloan", "Villanueva", "Jasaan", "Claveria", "Balingasag", "Laguindingan", "Alubijid", "Gitagum", "Libertad", "Initao", "Naawan", "Manticao", "Lugait", "Opol", "Salay", "Binuangan", "Sugbongcogon", "Kinoguitan", "Talisayan", "Medina"],
  "Mountain Province": ["Bontoc", "Sagada", "Tadian", "Bauko", "Besao", "Sabangan", "Sadanga", "Barlig", "Natonin", "Paracelis"],
  "Negros Occidental": ["Bacolod City", "Silay City", "Talisay City", "Victorias City", "Cadiz City", "Sagay City", "Escalante City", "San Carlos City", "Bago City", "La Carlota City", "Himamaylan City", "Kabankalan City", "Sipalay City", "Murcia", "Salvador Benedicto", "Manapla", "E.B. Magalona", "Pontevedra", "San Enrique", "Valladolid", "Pulupandan", "Candoni", "Cauayan", "Ilog", "Binalbagan", "Hinigaran", "Isabela", "La Castellana", "Moises Padilla", "Hinoba-an"],
  "Negros Oriental": ["Dumaguete City", "Bais City", "Tanjay City", "Bayawan City", "Canlaon City", "Guihulngan City", "Siaton", "Santa Catalina", "Zamboanguita", "Dauin", "Bacong", "Valencia", "Sibulan", "San Jose", "Amlan", "Mabinay", "Bindoy", "Ayungon", "Tayasan", "Jimalalud", "La Libertad", "Vallehermoso", "Manjuyod"],
  "Northern Samar": ["Catarman", "Laoang", "Allen", "Victoria", "Bobon", "San Isidro", "Biri", "Lavezares", "Rosario", "San Jose", "Mondragon", "San Roque", "Pambujan", "Catubig", "Las Navas", "Silvino Lobos", "Lapinig", "Gamay", "Mapanas", "Palapag", "Lope de Vega"],
  "Nueva Ecija": ["Cabanatuan City", "Gapan City", "San Jose City", "Palayan City", "Santa Rosa City", "Science City of Muñoz", "Aliaga", "Licab", "Quezon", "Zaragoza", "Santo Domingo", "Talavera", "Jaen", "San Antonio", "San Isidro", "Cabiao", "Peñaranda", "General Tinio", "Laur", "Gabaldon", "Bongabon", "Pantabangan", "Rizal", "Llanera", "Nampicuan", "Guimba", "Cuyapo", "Talugtug"],
  "Nueva Vizcaya": ["Bayombong", "Solano", "Bambang", "Villaverde", "Quezon", "Bagabag", "Diadi", "Ambaguio", "Kayapa", "Aritao", "Santa Fe", "Dupax del Norte", "Dupax del Sur", "Kasibu", "Alfonso Castaneda"],
  "Occidental Mindoro": ["Mamburao", "Sablayan", "San Jose", "Calintaan", "Rizal", "Santa Cruz", "Magsaysay", "Looc", "Lubang", "Paluan", "Abra de Ilog"],
  "Oriental Mindoro": ["Calapan City", "Pinamalayan", "Naujan", "Victoria", "Socorro", "Pola", "Bongabong", "Roxas", "Mansalay", "Bulalacao", "San Teodoro", "Baco", "Puerto Galera", "Gloria", "Bansud"],
  "Palawan": ["Puerto Princesa City", "Roxas", "Narra", "Quezon", "Brooke's Point", "Bataraza", "Rizal", "Sofronio Española", "Aborlan", "Kalayaan", "Coron", "Busuanga", "Culion", "El Nido", "San Vicente", "Taytay", "Araceli", "Dumaran", "Cuyo", "Magsaysay", "Agutaya", "Linapacan"],
  "Pampanga": ["San Fernando City", "Angeles City", "Mabalacat City", "Mexico", "Bacolor", "San Simon", "Santo Tomas", "Arayat", "Candaba", "San Luis", "Apalit", "Macabebe", "Masantol", "Minalin", "Guagua", "Sasmuan", "Lubao", "Floridablanca", "Porac", "Santa Rita"],
  "Pangasinan": ["Dagupan City", "San Carlos City", "Urdaneta City", "Alaminos City", "Lingayen", "Binmaley", "Calasiao", "Mangaldan", "Manaoag", "Villasis", "Rosales", "Tayug", "San Quintin", "Umingan", "Natividad", "San Nicolas", "Santa Maria", "Balungao", "Mapandan", "Laoac", "San Fabian", "Sual", "Labrador", "Mabini", "Burgos", "Dasol", "Agno", "Bani", "Bolinao", "Anda", "Infanta", "Bugallon", "Aguilar", "Urbiztondo", "Mangatarem", "Basista", "Malasiqui", "Bayambang", "Santa Barbara", "Bautista"],
  "Quezon": ["Lucena City", "Tayabas City", "Lucban", "Sariaya", "Candelaria", "Dolores", "San Antonio", "Tiaong", "Mauban", "Sampaloc", "Pagbilao", "Atimonan", "Perez", "Alabat", "Quezon", "Gumaca", "Plaridel", "Pitogo", "Unisan", "Agdangan", "Buenavista", "Mulanay", "San Narciso", "Catanauan", "General Luna", "Macalelon", "San Francisco", "San Andres", "Lopez", "Guinayangan", "Tagkawayan", "Calauag", "Infanta", "Real", "General Nakar", "Panukulan", "Burdeos", "Polillo", "Patnanungan", "Jomalig"],
  "Quirino": ["Cabarroguis", "Diffun", "Saguday", "Aglipay", "Maddela", "Nagtipunan"],
  "Rizal": ["Antipolo City", "Taytay", "Cainta", "Angono", "Binangonan", "Cardona", "Morong", "Baras", "Tanay", "Pililla", "Jalajala", "Rodriguez", "San Mateo", "Teresa"],
  "Romblon": ["Romblon", "Odiongan", "San Jose", "Santa Fe", "Looc", "Alcantara", "Ferrol", "Banton", "Corcuera", "Concepcion", "San Agustin", "Calatrava", "Magdiwang", "Cajidiocan", "Santa Maria"],
  "Samar": ["Catbalogan City", "Calbayog City", "Basey", "Marabut", "Santa Rita", "Villareal", "Talalora", "Daram", "Zumarraga", "Jiabong", "Paranas", "Hinabangan", "Calbiga", "Pinabacdao", "Motiong", "San Jorge", "Gandara", "Pagsanghan", "Tarangnan", "Almagro", "Santo Niño", "Tagapul-an", "San Jose de Buan", "Matuguinao"],
  "Sarangani": ["Alabel", "Malapatan", "Glan", "Malungon", "Maasim", "Kiamba", "Maitum"],
  "Siquijor": ["Siquijor", "Larena", "Enrique Villanueva", "Maria", "San Juan", "Lazi"],
  "Sorsogon": ["Sorsogon City", "Bulan", "Irosin", "Juban", "Casiguran", "Magallanes", "Barcelona", "Bulusan", "Santa Magdalena", "Matnog", "Donsol", "Pilar", "Castilla", "Gubat", "Prieto Diaz"],
  "South Cotabato": ["Koronadal City", "General Santos City", "Polomolok", "Tupi", "Tampakan", "T'boli", "Lake Sebu", "Surallah", "Banga", "Tantangan", "Norala", "Santo Niño"],
  "Southern Leyte": ["Maasin City", "Sogod", "Bontoc", "Libagon", "Padre Burgos", "Malitbog", "Tomas Oppus", "Macrohon", "Hinunangan", "Hinundayan", "Silago", "Saint Bernard", "San Juan", "Anahawan", "San Ricardo", "Limasawa", "Pintuyan", "Liloan"],
  "Sultan Kudarat": ["Isulan", "Tacurong City", "Lebak", "Kalamansig", "Palimbang", "Lambayong", "Sultan Kudarat", "Esperanza", "Bagumbayan", "Senator Ninoy Aquino", "Columbio", "Lutayan", "Presidente Quirino"],
  "Sulu": ["Jolo", "Indanan", "Parang", "Patikul", "Talipao", "Maimbung", "Siasi", "Tandubas", "Tapul", "Pangutaran", "Panamao", "Kalingalan Caluang", "Lugus", "Luuk", "Omar", "Pata", "Pitogo"],
  "Surigao del Norte": ["Surigao City", "Dapa", "General Luna", "Del Carmen", "Socorro", "Burgos", "San Benito", "Pilar", "San Isidro", "Santa Monica", "Alegria", "Claver", "Malimono", "Mainit", "Gigaquit", "Bacuag", "Placer", "Tagana-an", "Tubod", "Sison", "San Francisco"],
  "Surigao del Sur": ["Tandag City", "Bislig City", "Barobo", "Hinatuan", "Tagbina", "Lingig", "Marihatag", "San Agustin", "Lianga", "Tago", "Bayabas", "Carmen", "Lanuza", "Cortes", "Madrid", "Cantilan", "Carrascal", "Cagwait"],
  "Tarlac": ["Tarlac City", "Concepcion", "Capas", "Bamban", "Gerona", "Paniqui", "Moncada", "Camiling", "Mayantoc", "San Clemente", "Santa Ignacia", "Pura", "Ramos", "Anao", "San Manuel", "Victoria", "La Paz", "San Jose"],
  "Tawi-Tawi": ["Bongao", "Panglima Sugala", "Sibutu", "Sitangkai", "Tandubas", "Languyan", "Mapun", "Turtle Islands", "South Ubian", "Sapa-Sapa"],
  "Zambales": ["Olongapo City", "Iba", "Subic", "Castillejos", "San Marcelino", "San Antonio", "San Narciso", "San Felipe", "Cabangan", "Botolan", "Palauig", "Masinloc", "Candelaria", "Santa Cruz"],
  "Zamboanga del Norte": ["Dipolog City", "Dapitan City", "Sindangan", "Liloy", "Salug", "Manukan", "Siocon", "Sibuco", "Sirawai", "Labason", "Gutalac", "Godod", "Kalawit", "Tampilisan", "Bayog", "Siayan", "Sergio Osmeña Sr.", "Polanco", "Piñan", "President Manuel A. Roxas", "Mutia", "La Libertad", "Jose Dalman", "Katipunan"],
  "Zamboanga del Sibugay": ["Ipil", "Titay", "Kabasalan", "Naga", "Siay", "Buug", "Diplahan", "Imelda", "Mabuhay", "Malangas", "Olutanga", "Payao", "Roseller Lim", "Talusan", "Tungawan", "Alicia"],
  "Zamboanga del Sur": ["Pagadian City", "Zamboanga City", "Molave", "San Miguel", "Dinas", "Dimataling", "Pitogo", "Kumalarang", "Lapuyan", "Margosatubig", "Vincenzo A. Sagun", "Tabina", "Bayog", "Dumalinao", "Lakewood", "Tigbao", "Mahayag", "Aurora", "Tambulig", "Ramon Magsaysay", "Sominot", "Midsalip", "Josefina", "Labangan", "Tukuran", "Guipos", "San Pablo"],
};